FROM luyi/theano-blocks

MAINTAINER luyi

RUN pip3 install -r https://raw.githubusercontent.com/Lasagne/Lasagne/v0.1/requirements.txt

RUN pip2 install -r https://raw.githubusercontent.com/Lasagne/Lasagne/v0.1/requirements.txt

